### ISSUE TITLE
How many confirmations for ZCL to appear in my wallet?

### ISSUE THREAD

**Issue by xdemocle** [zencashio/eleos#10]
Hello, sorry to use this tool for making this question but i'm not getting very well how Eleos works.

I have this transaction:
http://aayanl.tech:3001/insight/tx/6ea9899c9009fc6cd59c50a7da1a4df33b3a94721812fc5911af58c4b3e29a0d

But my Eleos mac version installed locally doesn't show any incoming transactions.

To obtain a new transparent address, I went in "Receive" tab and clicked on "New Transparent address" button below.

**Comment by xdemocle** [comment]
Ok understood... only after an amount of confirmations I can see the transaction in my wallet. Thanks, I closed the issue.

**Comment by wilcollins** [comment]
@xdemocle how long did this take for you?

**Comment by xdemocle** [comment]
@wilcollins first of all, be sure your eleos is synced with network. check percentage status on bottom right.

**Comment by wilcollins** [comment]
@xdemocle it is synced -- I am actually waiting on the pool payout so I don't have any outstanding/pending transfers, I'm just wondering about the expected wait time when the payment is sent, basically how long it takes for the network to confirm/verify a transaction

**Comment by xdemocle** [comment]
when your eleos is synced, and a transaction is coming in, you will see it after 1 confirmation or even zero. generally doesn't took so much... we are not talking about bitcoin network 💃

**Comment by xdemocle** [comment]
if you wanna do a live test with ZCL or ZEN, then contact me privately via twitter. same nickname

**Comment by wilcollins** [comment]
I can only DM you on Twitter if you are following me @wilcollinsVT
