### ISSUE TITLE
No support for Zen actually?

### ISSUE THREAD

**Issue by reppolice** [zencashio/eleos#26]
The README on the frontpage does not mention Zen, despite the obvious connection to zencash. Is Zen support not there at all perhaps? I tried importing my Zen wallet back from Linux and I get Javascript errors on Windows. Also, the addresses that eleos produces look like zec/zcl addresses, presumably the message saying it is syncing with the zcl network is accurate?

**Comment by aayanl** [comment]
We haven't released the binaries yet, still undergoing QA
