### ISSUE TITLE
Does not work 5 version

### ISSUE THREAD

**Issue by Aleksandr17** [zencashio/eleos#34]
I have a MacBook
Generally installed a purse 5 version nothing happens blocks do not load!
Removed and reinstalled 4 version all ok
Please fix 5 version

**Comment by xdemocle** [comment]
@Aleksandr17  Read the issues list before open a new ticket. Some guy is working on it for mac and win version.

**Comment by LukasBures** [comment]
#35 duplicity, try version v0.0.6, closed
