### ISSUE TITLE
Receiving error listed in body text on Mac running El Capitan

### ISSUE THREAD

**Issue by ejdevs** [zencashio/eleos#35]
**zend-mac cannot be opened because of a problem.**

Check with the developer to make sure zend-mac works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.
Click Report to see more detailed information and send a report to Apple.

![screen shot 2017-06-04 at 12 31 50 pm](https://cloud.githubusercontent.com/assets/16732552/26763899/d8efab06-4921-11e7-921f-303f9e6f3c32.png)

**Comment by LukasBures** [comment]
Version 0.0.5 was checked on macOS Sierra.

**Comment by LukasBures** [comment]
v0.0.6 try it please ... 

If that not work for you, we will need to solve signing by Apple Development ID.
