### ISSUE TITLE
eleos-win64-v0.0.5.zip not posted for download

### ISSUE THREAD

**Issue by needA-zenWallet** [zencashio/eleos#47]
I believe this to be the only SW to create a ZEN wallet, so with out the download link, there's no way to get a ZEN wallet.  The sha256 security hashes are there for the file but no download link.  Need eleos-win64-v0.0.5.zip

**Comment by panterateama** [comment]
same here, i have been trying to dump in the files from the 0.0.5 source but its not working. There is no alternative to create a local wallet that i can find and the link is gone. Please repost the link :)

Thanks!

**Comment by ionrk** [comment]
Yep, need too this 0.0.5 ver eleos/

**Comment by myk1984** [comment]
hellow!
How I can Download  eleos-win64-v0.0.5.zip? It's posable?

**Comment by LukasBures** [comment]
go to new official github please
https://github.com/ZencashOfficial/eleos/releases

**Comment by panterateama** [comment]
Thank you for the email Lukas!

On Jun 12, 2017 8:03 AM, Lukáš Bureš <notifications@github.com> wrote:

go to new official github please
https://github.com/ZencashOfficial/eleos/releases

**Comment by myk1984** [comment]
Thanks 



Отправлено из мобильной Почты Mail.Ru


понедельник, 12 июня 2017 г., 16:07 +0300 от panterateama  <notifications@github.com>:
>Thank you for the email Lukas!
>

**Comment by myk1984** [comment]
Thanks 



Отправлено из мобильной Почты Mail.Ru


понедельник, 12 июня 2017 г., 15:03 +0300 от Lukáš Bureš  <notifications@github.com>:
