### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by lelbo** [zencashio/eleos#48]
Hello, i have Eleos 0.0.5
I need Update : 

backup your ZEN wallet.dat if you have some ZEN in it
delete %APPDATA%/Zen and %APPDATA%/ZcashParams
run Eleos v0.0.6

But no download for 0.0.6  and how to update   

Tank you for Job

**Comment by LukasBures** [comment]
go to new official github please
https://github.com/ZencashOfficial/eleos/releases
