### ISSUE TITLE
Handle special characters in the coin config file

### ISSUE THREAD

**Issue by cronicc** [zencashio/eleos#6]
Eleos fails to start the coin daemon if the `rpcpassword` contains special characters like `/\?` and hangs at `initializing`. When `rpcpassword`  contains `%` it fails with the following js error:

![eleos](https://cloud.githubusercontent.com/assets/23322296/25130988/7b5222aa-2444-11e7-8cfd-20e6e4a8e801.png)

**Comment by joshuayabut** [comment]
Should be fixed now with the above commit.
